// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB65RZEbv6J8dzBzKuYyM7BRHv295nbbHg',
    appId: '1:257328771711:android:f9cf8802516c6b2033454a',
    messagingSenderId: '257328771711',
    projectId: 'faktura-nft-viewer',
    storageBucket: 'faktura-nft-viewer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhxQ0cjIR6dnR0clSSg-EfPnzoABRmTVs',
    appId: '1:257328771711:ios:f0173c82e377ab0033454a',
    messagingSenderId: '257328771711',
    projectId: 'faktura-nft-viewer',
    storageBucket: 'faktura-nft-viewer.appspot.com',
    iosClientId: '257328771711-upnstngs77i86ebaajk0t1lj1ei0g1u0.apps.googleusercontent.com',
    iosBundleId: 'faktura.art',
  );
}
